import { CheckCircle2, ClipboardList, MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { publishCartMessage } from "@/lib/utils";
import { WA_PUBLISH, buildWAUrl } from "@/config/whatsapp";

function Text({ en, ta }: { en: string; ta: string }) {
  return (
    <>
      <span className="en">{en}</span>
      <span className="ta tamil-text">{ta}</span>
    </>
  );
}

const details = [
  ["Your Name", "உங்கள் பெயர்"],
  ["Phone Number", "தொலைபேசி எண்"],
  ["Number of Carts Available", "எத்தனை வண்டிகள் உள்ளன"],
  ["Cart Type (with stove / without stove / with top / etc.)", "வண்டி வகை (அடுப்பு / மேல் கவர் / அடுப்பு இல்லாதது)"],
  ["Rental Price You Expect (per day)", "எதிர்பார்க்கும் ஒரு நாள் வாடகை விலை"],
  ["Location in Coimbatore", "கோவையில் உங்கள் பகுதி"],
  ["Cart Photos (send on WhatsApp)", "வண்டி படங்கள் (வாட்ஸ்அப்பில் அனுப்பவும்)"]
];

const benefits = [
  ["Reach more rental customers", "அதிக வாடகை வாடிக்கையாளர்களை அடையுங்கள்"],
  ["Earn from idle carts", "பயன்படாத வண்டிகள் மூலம் வருமானம் ஈட்டுங்கள்"],
  ["Get listed in a premium marketplace", "பிரீமியம் சந்தையில் உங்கள் வண்டியை பதிவு செய்யுங்கள்"],
  ["Expanding network across Tamil Nadu", "தமிழ்நாடு முழுவதும் விரிவடையும் சேவை"],
  ["Agree platform fee before listing", "பதிவு செய்வதற்கு முன் கட்டணத்தை ஒப்புக்கொள்ளுங்கள்"]
];

export default function PublishPage() {
  return (
    <main className="bg-[#F8F6F2] pt-16 md:pt-28">
      {/* Dynamic SEO Meta Tags are generated by metadata config in layout/page metadata */}
      <section className="pb-20 pt-24 md:pb-24 md:pt-0">
        <div className="site-container grid gap-6 md:grid-cols-[0.95fr_1.05fr] md:gap-6">
          <div className="flex flex-col justify-between">
            <div>
              <p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">
                <Text en="Vendor Network" ta="வண்டி உரிமையாளர் நெட்வொர்க்" />
              </p>
              <h1 className="mt-3 font-display text-5xl uppercase leading-none text-ink md:text-7xl">
                <Text en="Publish Your Cart on Thalluvandi" ta="என் வண்டி சேர்க்க" />
              </h1>
              <p className="mt-6 max-w-[680px] text-lg leading-8 text-muted">
                <Text 
                  en="If you own a food cart and want more rental customers, publish it on Thalluvandi. We are rapidly expanding our network across all Tamil Nadu districts!" 
                  ta="உங்களுக்கு தள்ளுவண்டி இருந்தால் தள்ளுவண்டி தளத்தில் உங்கள் வண்டியை பதிவு செய்யுங்கள் — தமிழ்நாடு முழுவதும் நாங்கள் வேகமாக விரிவடைந்து வருகிறோம், வாடிக்கையாளர்களை நாங்க தர்றோம்!" 
                />
              </p>
            </div>
            <Button asChild size="lg" className="mt-8 bg-[#25D366] hover:bg-[#20ba5a] text-white">
              <a href={buildWAUrl(WA_PUBLISH, publishCartMessage)} target="_blank">
                <MessageCircle size={18} /> <Text en="📋 List My Cart" ta="📋 என் வண்டி சேர்க்க" />
              </a>
            </Button>
          </div>

          <div className="rounded-2xl border border-black/10 bg-white p-6 shadow-premium md:p-8">
            <h2 className="font-display text-5xl uppercase leading-none text-ink">
              <Text en="To list your cart, share these details on WhatsApp:" ta="பதிவு செய்ய இந்த விவரங்களை வாட்ஸ்அப்பில் பகிரவும்:" />
            </h2>
            <div className="mt-8 grid gap-3">
              {details.map(([detail, tamil]) => (
                <div key={detail} className="flex items-start gap-3 rounded-xl border border-black/10 bg-[#F8F6F2] p-4 text-left font-bold text-ink">
                  <ClipboardList className="mt-0.5 shrink-0 text-primary animate-pulse" />
                  <span>
                    <Text en={detail} ta={tamil} />
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section className="pb-24">
        <div className="site-container">
          <div className="rounded-2xl border border-black/10 bg-white p-6 md:p-8">
            <h2 className="font-display text-5xl uppercase leading-none text-ink">
              <Text en="Why publish?" ta="ஏன் பதிவு செய்ய வேண்டும்?" />
            </h2>
            <div className="mt-8 grid gap-4 md:grid-cols-2 md:gap-6">
              {benefits.map(([benefit, tamil]) => (
                <div key={benefit} className="flex min-h-14 items-center gap-3 rounded-xl border border-black/10 bg-[#F8F6F2] p-4 text-left font-bold text-ink">
                  <CheckCircle2 className="shrink-0 text-primary" />
                  <Text en={benefit} ta={tamil} />
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="pb-24">
        <div className="site-container max-w-4xl">
          <p className="text-xs font-bold uppercase tracking-[0.2em] text-primary text-center">
            <Text en="FAQ" ta="கேள்வி பதில்" />
          </p>
          <h2 className="mt-3 font-display text-4xl uppercase leading-none text-ink text-center md:text-5xl">
            <Text en="Publishing Carts FAQ" ta="வண்டிகள் பதிவு கேள்வி பதில்" />
          </h2>

          <div className="mt-12 space-y-4">
            {publishFaqs.map(([question, tamilQuestion, answer, tamilAnswer]) => (
              <details
                key={question}
                className="group rounded-2xl border border-black/10 bg-white p-6 [&_summary::-webkit-details-marker]:hidden"
              >
                <summary className="flex cursor-pointer items-center justify-between gap-1.5 text-ink font-bold">
                  <h3 className="font-display text-xl uppercase tracking-wide leading-tight">
                    <Text en={question} ta={tamilQuestion} />
                  </h3>
                  <span className="shrink-0 rounded-full bg-orange-50 border border-orange-200/50 p-1.5 text-primary group-open:-rotate-180 transition duration-300">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-4 w-4"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      strokeWidth="3"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M19 9l-7 7-7-7"
                      />
                    </svg>
                  </span>
                </summary>
                <p className="mt-3 text-[0.95rem] leading-7 text-muted border-t border-black/5 pt-3">
                  <Text en={answer} ta={tamilAnswer} />
                </p>
              </details>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}

const publishFaqs = [
  [
    "How can I publish my cart on Thalluvandi?",
    "என் வண்டியை தள்ளுவண்டி தளத்தில் எப்படி சேர்ப்பது?",
    "Simply click the 'List My Cart' button to start a WhatsApp chat with our team. Share your name, phone number, location, cart type, expected daily rent, and clear photos. Once verified, we will list it on our premium platform for customers to book.",
    "எங்கள் 'என் வண்டி சேர்க்க' பட்டனைக் கிளிக் செய்து எங்களை வாட்ஸ்அப்பில் தொடர்பு கொள்ளவும். உங்கள் பெயர், வண்டியின் படங்கள், இருப்பிடம், எதிர்பார்க்கும் வாடகை விலை மற்றும் வண்டியின் விவரங்களை அனுப்புங்கள். சரிபார்க்கப்பட்ட பின் எங்கள் தளத்தில் பதிவு செய்யப்படும்.",
  ],
  [
    "What is the commission/platform fee?",
    "தள்ளுவண்டி தளத்தின் கமிஷன் / சேவை கட்டணம் எவ்வளவு?",
    "Listing your cart is completely free. We only charge a small platform fee or commission when a customer successfully books your cart through our marketplace. The exact fee is discussed and agreed upon before listing.",
    "வண்டியைப் பதிவு செய்வது முற்றிலும் இலவசம். உங்கள் வண்டியை வாடிக்கையாளர்கள் எங்கள் தளம் வழியாக புக் செய்யும் போது மட்டுமே ஒரு சிறிய சேவை கட்டணம் (Platform fee) வசூலிக்கப்படும். இதன் விவரங்களை முன்பே பேசி உறுதி செய்துகொள்ளலாம்.",
  ],
  [
    "Who handles the delivery and return of published carts?",
    "வண்டியை டெலிவரி செய்வதும் திரும்பப் பெறுவதும் யார் பொறுப்பு?",
    "Logistics and transport are typically handled by the renter. However, as the vendor/owner, you must ensure the cart is in a clean, fully functional condition at your specified location for pickup.",
    "போக்குவரத்து மற்றும் டெலிவரி பொதுவாக வாடகைக்கு எடுக்கும் நபரின் பொறுப்பாகும். ஆனால் வண்டி நல்ல முறையில் இயங்கும் நிலையிலும், சுத்தமாகவும் இருப்பதை வண்டியின் உரிமையாளரான நீங்கள் உறுதி செய்ய வேண்டும்.",
  ],
  [
    "How do I get paid for rentals?",
    "என் வண்டிக்கான வாடகை எனக்கு எப்படி கிடைக்கும்?",
    "Rental payouts are transferred directly to you via UPI or Cash weekly, or as per the custom payout frequency we establish with you upon listing.",
    "வண்டிக்கான வாடகை வாராந்திர அடிப்படையில் UPI அல்லது ரொக்கமாக (Cash) நேரடியாக உங்களிடம் ஒப்படைக்கப்படும். அல்லது பதிவு செய்யும் போது பேசப்படும் ஒப்பந்தத்தின்படி வழங்கப்படும்.",
  ],
];
